logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    cn.itcast.mq: info

#导入amqp消息队列依赖之后 添加配置连接mq
spring:
  rabbitmq:
    host: 192.168.12.132 #mq所在的主机
    port: 5672  #服务所占用的端口 15672是管理端口
    virtual-host: / #虚拟主机
    username: itcast #用户名
    password: 123321 #用户密码
    publisher-confirm-type: correlated  #开启publish-confirm correlated异步回调
    publisher-returns: true    #开启publisher return
    template:
      mandatory: true   #定义消息路由失败的策略，true则调用ReturnCallback，false直接丢弃消息