server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice #eureka客户端服务名
  #nacos配置
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
      discovery:
        cluster-name: HZ #集群名称 这里HZ代指杭州 ，可以自己指定名称
        namespace: #命名空间的uuid 指定命名空间
        ephemeral: false  #是否是临时实例  我们将其变成非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: #eureka地址
#      defaultZone: http://127.0.0.1:10086/eureka

#yml文件配置负载均衡规则
userservice: #eureka客户端服务名
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #指定负载均衡为随机
    #此配置优先访问当前集群内的服务器 如HZ
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#Ribbon饥饿加载
ribbon:  #ribbon默认策略是 懒加载 第一次加载耗时长 后续加载从内存中获取 耗时慢
  eager-load:
    enabled: true  #默认是false 不开启饥饿加载
    clients: userservice  #指定对谁开启饥饿加载  这里是userservice -eureka客户端服务

---
#配置feign的日志级别 默认是none
feign:
  client:
    config:
      default:   #如果写默认就是全局配置  局部配置写服务的名称
        logger-level: basic   #有四种：none basic header full
  #配置feign httpclient连接池
  httpclient:
    enabled: true  #开启feign对HttpClient的支持
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #每个路径上的最大连接数