logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    root: info

#导入amqp消息队列依赖之后 添加配置连接mq
spring:
  rabbitmq:
    host: 192.168.12.132 #mq所在的主机
    port: 5672  #服务所占用的端口 15672是管理端口
    virtual-host: / #虚拟主机
    username: itcast #用户名
    password: 123321 #用户密码
    publisher-confirm-type: correlated  #开启publish-confirm correlated异步回调
    publisher-returns: true    #开启publisher return
    template:
      mandatory: true   #定义消息路由失败的策略，true则调用ReturnCallback，false直接丢弃消息
    listener:
      simple:        #消费者处理消息后可以向MQ发送ack回执，收到后会删除该消息
        prefetch: 1
        acknowledge-mode: auto  #none 关闭ack manual 手动ack auto 自动ack 默认none
    #none模式 MQ假定消费者获取消息之后会处理，消息发送后直接删除
    #auto模式 spring检测监听（listener）代码是否出现异常，如果没有出现异常 返回ack 出现异常返回nack
    #auto模式下如果出现异常会重新发送消息
    #manual模式 手动ack 需要在业务结束之后 调用api发送ack
        retry:  #retry开启消息重发机制
          enabled: true   #开启消费者重试失败
          initial-interval: 1000  #初始化失败等待时长为1秒
          multiplier: 1  #下次失败的等待时长， 这里是1倍 ，由上次等待时长乘以这个倍数
          max-attempts: 3 #最大重试次数
          stateless: true  #true无状态，false有状态 ，如果业务中包含事务 就要把这里改为false