logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#导入amqp消息队列依赖之后 添加配置连接mq
spring:
  rabbitmq:
    host: 192.168.12.132 #mq所在的主机
    port: 5672  #服务所占用的端口 15672是管理端口
    virtual-host: / #虚拟主机
    username: itcast #用户名
    password: 123321 #用户密码