server:
  port: 10010 #网关端口
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: nacos:8848 #nacos服务地址 注册到nacos中
    gateway:
      routes:  #网关路由配置 路由不止一个 用-分割
        - id: user-service #路由标识 必须唯一 名称不固定
          uri: lb://userservice #路由目标地址 lb=loadbalance-负载均衡 userservice对应服务名
          predicates:  #路由断言 判断请求是否符合规则
            - Path=/user/** #路径断言，判断路径是否是以/user开头，如果是则符合条件 不是则不会进行
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
          #filters: #添加过滤器 对请求或向响应做加工处理
           # - AddRequestHeader=Truth,lnc is freaking aowsome!  #给order每个请求添加请求头
      #配置默认过滤器规则， default-filters  跟routes在同一级目录下 对所有请求生效
      default-filters:
        - AddRequestHeader=Truth,lnc is freaking aowsome!
      globalcors: #全局跨域处理
        add-to-simple-url-handler-mapping: true  #解决options请求被拦截问题
        corsConfigurations:
          '[/**]':   #拦截所有
             allowedOrigins: #允许哪些网站的跨域请求
               - "http://localhost:8090"
               - "http://www.leyou.com"
               - "http://localhost:5500"
             allowedMethods: #允许的跨域ajax的请求方式
               - "GET"
               - "POST"
               - "DELETE"
               - "PUT"
               - "OPTIONS"
             allowedHeaders: "*"  #允许在请求中携带的头信息
             allowCredentials: true  #是否允许携带cookie
             maxAge: 360000  #这次跨域检测的有效期