server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #elasticsearch:
   # rest:
    #  uris: 192.168.12.132
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo

